openapi: 3.0.0
info:
  title: To Do List API
  version: 1.0.0
  description: A simple To Do List API
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /todos:
    get:
      summary: Get all todos
      tags:
        - Todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Todo created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input
  /todos/{id}:
    put:
      summary: Update a todo
      tags:
        - Todos
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id of the todo to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Todo updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    delete:
      summary: Delete a todo
      tags:
        - Todos
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id of the todo to delete
      responses:
        '204':
          description: Todo deleted
        '404':
          description: Todo not found

components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - task
      properties:
        id:
          type: string
          description: Unique identifier for the todo
        task:
          type: string
          description: Description of the todo task
        completed:
          type: boolean
          description: Status of the todo
      example:
        id: "1"
        task: "example task"
        completed: false
